export { default as SignUp } from './SignUp/SignUp'
export { default as SignIn } from './SignIn/SignIn'
export { default as Home } from './Home/Home'
export { default as CreatePost } from './CreatePost/CreatePost'
export { default as UserProfile } from './UserProfile/UserProfile'
export { default as DetailedPost } from './DetailedPost/DetailedPost'
export { default as Comments } from './Comments/Comments'